<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\Icons\SpotifyReleaseUpdater_48px.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Pictures\SpotifyReleaseUpdater.png" />
    <None Remove="Assets\SpotifyReleaseUpdater.ico" />
    <None Remove="PythonBackend\.cache" />
    <None Remove="PythonBackend\.env" />
    <None Remove="PythonBackend\config.json" />
    <None Remove="PythonBackend\main.exe" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Icons\SpotifyReleaseUpdater_48px.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Pictures\SpotifyReleaseUpdater.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="PythonBackend\.cache">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="PythonBackend\.env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="PythonBackend\config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="PythonBackend\main.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CustomWFUI">
      <HintPath>..\..\CustomWFUI\CustomWFUI\bin\Debug\CustomWFUI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="PythonBackend\spotify_backend.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>